### ISSUE TITLE
Changes discussed in bioimage.io meeting dec 4

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/configuration#57]
Overview of the changes discussed and the PRs to introduce them for them from the last meeting.

- [x] add `run_mode`, #51 
- [x] change the author definition (author goes to `weights`, add `parent` field to authors and weights), see #59 
- [x] shape descriptions (halo not part of how we compute the output shape), see #59 
- [x] update the model framework, see #50
- [x] change how we indicate optional fields
